[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "hypr-notepad"
version = "1.0.0"
description = "A quick terminal notepad for Hyprland"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [{ name = "Goncsal" }]
classifiers = [
  "Environment :: X11 Applications :: GTK",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3",
]

[project.scripts]
hypr-notepad = "hypr_notepad.app:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
hypr_notepad = ["style.css"]

