# Quick notepad
bind = $mainMod, N, exec, hypr-notepad
windowrulev2 = float, title:^(New note)$
windowrulev2 = center, title:^(New note)$
windowrulev2 = float, title:^(Hypr Notepad.*)$
windowrulev2 = size 360 360, title:^(Hypr Notepad.*)$
windowrulev2 = move 69.5% 5.037%, title:^(Hypr Notepad.*)$
