# Quick notepad
bind = $mainMod, N, exec, hypr-notepad
windowrulev2 = float, class:^(io.github.goncsal.HyprNotepad)$
windowrulev2 = center, class:^(io.github.goncsal.HyprNotepad)$
windowrulev2 = size 720 480, class:^(io.github.goncsal.HyprNotepad)$
