#!/usr/bin/env bash

set -o nounset
set -o pipefail

address=${1:-}
[[ $address =~ ^0x[0-9a-fA-F]+$ ]] || exit 2

monitor_id=
window_width=
for _ in {1..20}; do
    clients=$(hyprctl clients -j) || exit 1
    read -r monitor_id window_width < <(
        jq -r --arg address "$address" \
            '.[] | select(.address == $address) | [.monitor, .size[0]] | @tsv' \
            <<<"$clients"
    )
    [[ -n ${monitor_id:-} && -n ${window_width:-} ]] && break
    sleep 0.05
done
[[ -n ${monitor_id:-} && -n ${window_width:-} ]] || exit 1

monitors=$(hyprctl monitors -j) || exit 1
read -r monitor_x monitor_y monitor_width monitor_height monitor_scale reserved_left reserved_top reserved_right reserved_bottom < <(
    jq -r --argjson id "$monitor_id" \
        '.[] | select(.id == $id) | [.x, .y, .width, .height, .scale, .reserved[0], .reserved[1], .reserved[2], .reserved[3]] | @tsv' \
        <<<"$monitors"
)
border=$(hyprctl getoption general:border_size -j | jq -r '.int') || exit 1

read -r target_x target_y < <(
    awk -v mx="$monitor_x" -v my="$monitor_y" -v mw="$monitor_width" -v mh="$monitor_height" \
        -v scale="$monitor_scale" -v rl="$reserved_left" -v rt="$reserved_top" \
        -v rr="$reserved_right" -v rb="$reserved_bottom" -v border="$border" -v ww="$window_width" \
        'BEGIN {
            usable_w = (mw / scale) - rl - rr - (2 * border)
            usable_h = (mh / scale) - rt - rb - (2 * border)
            x = mx + (mw / scale) - rr - border - ww - (usable_w * (3 / 1194))
            y = my + rt + border + (usable_h * (2 / 640))
            printf "%d %d\n", int(x + 0.5), int(y + 0.5)
        }'
)

hyprctl dispatch \
    "hl.dsp.window.move({ x = $target_x, y = $target_y, window = \"address:$address\" })" \
    >/dev/null
